### ISSUE TITLE
seloader skip checking PE and p7b signature

### ISSUE THREAD

**Issue by yunguowei** [jiazhang0/SELoader#2] opened 2017-10-16 11:18 UTC
Hi Jia,
I'm running into a problem, with upstream SecureCore on qemu, grubx64.efi and grub.cfg.p7b checking are bypassed. For example,  if grub.cfg.p7b is removed or grubx64.efi is signed by a unknown key, seloader can boot grub, which is not an expected behavior.

Sounds in MokVerifyProtocolInstalled(), seloader can't locate gEfiMokVerifyProtocolGuid, see:

Status = EfiProtocolLocate(&gEfiMokVerifyProtocolGuid,
				   (VOID **)&MokVerifyProtocol);

I  guess gEfiMokVerifyProtocolGuid is installed by shim loader, but why this protocol is not located by seloader? 

Can you help with this?

Thanks,
Yunguo

**Comment by jiazhang0** [comment] 2017-10-16 12:13
@yunguowei It is possible that shim installs the MOK protocol but disables MOK secure boot. I will check whether it is there.

**Comment by jiazhang0** [comment] 2017-10-18 15:12
@yunguowei I can reproduce this issue. The root cause is due to calling fallback, leading shim uninstalling MOK Verify Protocol. Getting rid of this logic is simple, but this means shim has to be patched and this modification would be rejected by Redhat's reviewers when you are requesting MSFT signing.

**Comment by yunguowei** [comment] 2017-10-19 02:01
@jiazhang0 
Yes, I have found out that fallback introduced this issue. But still not locate where(source code) fallback uninstall shim's MOK Verify Protocal. Can you advise more about it?
fallback has some issue with setting BootOrder on NUC boards. SELoaderx64.efi is set to BootOrder and this leads to UEFI SB verify failed.

MSFT signing might not be a priority for now, so I would like to take fallback away. What do you think?

**Comment by jiazhang0** [comment] 2017-10-19 14:29
@yunguowei I agree with dropping fallback anyway. Introducing fallback is intended to work around MSFT signing review which needs to touch shim source code. However fallback cannot work with SELoader well. Note that dropping fallback still blocks MSFT signing review, unless you would like to exchange the names between SELoader to grub.

Next I will do the items below this weekend.
- Drop fallback boot flow
- Update READM
- Update shim to the latest

**Comment by jiazhang0** [comment] 2017-10-27 15:36
@yunguowei This issue is resolved in the latest meta-secure-core.

**Closed by jiazhang0** 2017-10-27 15:36 UTC
